<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\UserResource\Widgets\UserOverview;
use App\Models\User;
use AymanAlhattami\FilamentPageWithSidebar\FilamentPageSidebar;
use AymanAlhattami\FilamentPageWithSidebar\PageNavigationItem;
use Carbon\Carbon;
use Filament\Forms;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class UserResource extends Resource
{
    protected static ?string $model = User::class;

    protected static ?string $navigationIcon = 'heroicon-o-users';

    protected static ?string $navigationGroup = 'Administração';

    protected static ?string $navigationLabel = 'Usuários';

    protected static ?string $modelLabel = 'Usuários';

    protected static ?string $recordTitleAttribute = 'name';

    public static function canAccess(): bool
    {
        return auth()->user()->hasRole('admin');
    }

    /*** @param Model $record
     * @return string
     */
    public static function getGlobalSearchResultTitle(Model $record): string
    {
        return $record->name; // TODO: Change the autogenerated stub
    }

    /*** @return string[]
     */
    public static function getGloballySearchableAttributes(): array
    {
        return ['name', 'email']; // TODO: Change the autogenerated stub
    }

    /*** @param Model $record
     * @return FilamentPageSidebar
     */
    public static function sidebar(Model $record): FilamentPageSidebar
    {
        return FilamentPageSidebar::make()
            ->setTitle($record->name)
            ->setDescription($record->created_at)
            ->setNavigationItems([
                PageNavigationItem::make(__('base.list_user'))
                    ->translateLabel()
                    ->url(static::getUrl('index'))->icon('heroicon-o-user-group')
                    ->isActiveWhen(function () {
                        return request()->routeIs(static::getRouteBaseName().'.list-users');
                    }),
                PageNavigationItem::make(__('base.view_user'))
                    ->translateLabel()
                    ->url(static::getUrl('view', ['record' => $record->id]))->icon('heroicon-o-user')
                    ->isActiveWhen(function () {
                        return request()->routeIs(static::getRouteBaseName().'.view');
                    }),
                PageNavigationItem::make(__('base.edit_user'))
                    ->translateLabel()
                    ->url(static::getUrl('edit', ['record' => $record->id]))
                    ->icon('heroicon-o-pencil-square')
                    ->isActiveWhen(function () {
                        return request()->routeIs(static::getRouteBaseName().'.edit');
                    }),
                PageNavigationItem::make(__('base.change_password'))
                    ->translateLabel()
                    ->url(static::getUrl('password.change', ['record' => $record->id]))
                    ->icon('heroicon-o-key')
                    ->isActiveWhen(function () {
                        return request()->routeIs(static::getRouteBaseName().'.password.change');
                    }),

            ]);
    }

    /*** @param Form $form
     * @return Form
     */
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make()
                    ->schema([
                        Forms\Components\TextInput::make('name')
                            ->label('Nome')
                            ->placeholder('Digite o nome')
                            ->required()
                            ->maxLength(191),
                        Forms\Components\TextInput::make('email')
                            ->label('E-mail')
                            ->placeholder('Digite o e-mail')
                            ->email()
                            ->required()
                            ->unique(ignorable: fn ($record) => $record)
                            ->maxLength(191),
                        Forms\Components\TextInput::make('cpf')
                            ->label('NIF')
                            ->placeholder('Digite o NIF')
                            ->maxLength(191),
                        Forms\Components\TextInput::make('phone')
                            ->label('Telefone')
                            ->placeholder('Digite o Telefone')
                            ->maxLength(191),
                        Forms\Components\Select::make('inviter')
                            ->label('Afiliado')
                            ->placeholder('Selecione um afiliado')
                            ->relationship(name: 'affiliate', titleAttribute: 'name')
                            ->options(
                                fn ($get) => User::query()->pluck('name', 'id')
                            )
                            ->searchable()
                            ->preload()
                            ->live(),
                        Forms\Components\DateTimePicker::make('email_verified_at')
                            ->label('Verificação E-mail'),
                    ])->columns(3),
                Forms\Components\Section::make('Configurações de Comissão')
                    ->schema([
                        Forms\Components\TextInput::make('affiliate_revenue_share')
                            ->label('Revenue Share (%)')
                            ->required()
                            ->default(2)
                            ->numeric(),
                        Forms\Components\TextInput::make('affiliate_revenue_share_fake')
                            ->label('Revenue Share Fake (%)')
                            ->numeric(),
                        Forms\Components\TextInput::make('affiliate_cpa')
                            ->label('CPA')
                            ->default(10)
                            ->required()
                            ->numeric(),
                        Forms\Components\TextInput::make('affiliate_baseline')
                            ->label('Baseline')
                            ->default(40)
                            ->required()
                            ->numeric(),
                    ])->columns(4),

                Forms\Components\Section::make('Configurações de Visualização do Painel')
                    ->description('Controle quais elementos são visíveis para o afiliado no painel')
                    ->schema([
                        Forms\Components\Toggle::make('revshare_visible')
                            ->label('Mostrar card de Revenue Share')
                            ->helperText('Se ativado, o card de Revenue Share será visível para este usuário no painel de afiliados')
                            ->default(false),
                    ])->columns(1),
                Forms\Components\Section::make('Controle de CPA')
                    ->schema([
                        Forms\Components\Toggle::make('cpa_enabled')
                            ->label('CPA Ativo')
                            ->helperText('Ative ou desative o CPA para este usuário')
                            ->default(true),
                        Forms\Components\TextInput::make('cpa_percentage')
                            ->label('Porcentagem de Contagem do CPA')
                            ->helperText('Define quantas vezes (em %) o CPA será contado. Ex: 90 para contar 90% das vezes')
                            ->default(100)
                            ->numeric()
                            ->minValue(0)
                            ->maxValue(100)
                            ->suffix('%'),
                        Forms\Components\TextInput::make('affiliate_register_percentage')
                            ->label('Porcentagem de Cadastros Visíveis')
                            ->helperText('Define quantos cadastros (em %) o afiliado poderá ver. Ex: 90 para mostrar 90% dos cadastros')
                            ->default(100)
                            ->numeric()
                            ->minValue(0)
                            ->maxValue(100)
                            ->suffix('%'),
                    ])->columns(3),
                Forms\Components\Section::make('Configurações de Jogos de Habilidade')
                    ->schema([
                        Forms\Components\TextInput::make('skill_games_min_amount')
                            ->label('Valor Mínimo para Jogos de Habilidade')
                            ->helperText('Define o valor mínimo de entrada para jogos de habilidade. Se nulo, será usado o valor padrão do jogo.')
                            ->numeric()
                            ->nullable()
                            ->placeholder('Valor padrão do jogo'),
                        Forms\Components\TextInput::make('skill_games_max_amount')
                            ->label('Valor Máximo para Jogos de Habilidade')
                            ->helperText('Define o valor máximo de entrada para jogos de habilidade. Se nulo, será usado o valor padrão do jogo.')
                            ->numeric()
                            ->nullable()
                            ->placeholder('Valor padrão do jogo'),
                        Forms\Components\Select::make('skill_games_difficulty')
                            ->label('Dificuldade dos Jogos de Habilidade')
                            ->helperText('Define a dificuldade personalizada para todos os jogos de habilidade (Pacman, Subway Surfers, Jetpack, etc.). Se nulo, será usado o valor padrão do jogo.')
                            ->options(config('kyc.skill_games_difficulty_options'))
                            ->nullable()
                            ->placeholder('Dificuldade padrão do jogo'),
                    ])->columns(3),
                Forms\Components\Section::make('Configurações do Mines')
                    ->schema([
                        Forms\Components\TextInput::make('mines_win_chance')
                            ->label('Chance de Vitória (%)')
                            ->helperText('Defina a porcentagem de chance de vitória (0-100). Se deixar em branco, usará a Configuração Global.')
                            ->numeric()
                            ->minValue(0)
                            ->maxValue(100)
                            ->suffix('%')
                            ->nullable()
                            ->dehydrateStateUsing(fn ($state) => $state === '' ? null : $state)
                            ->placeholder('Aleatório (Padrão)'),
                    ])->columns(1),
                Forms\Components\Section::make()
                    ->schema([
                        Forms\Components\Toggle::make('banned')
                            ->label('Banido')
                            ->helperText('Quando ativado, o usuário será automaticamente deslogado')
                            ->afterStateUpdated(function ($state, $record, $get) {
                                if ($record) {
                                    // Para JWT, não podemos invalidar tokens diretamente
                                    // O middleware CheckUserBanned irá impedir o acesso de usuários banidos

                                    // Registrar a ação de banimento/desbanimento
                                    $action = $state ? 'ban' : 'unban';
                                    $logMessage = $state ? 'user_banned' : 'user_unbanned';
                                    $banReason = $get('ban_reason');

                                    activity()
                                        ->causedBy(auth()->user())
                                        ->performedOn($record)
                                        ->withProperties([
                                            'action' => $action,
                                            'banned' => $state,
                                            'ban_reason' => $banReason,
                                            'admin_id' => auth()->id(),
                                            'admin_name' => auth()->user()->name,
                                        ])
                                        ->log($logMessage);
                                }
                            })
                            ->dehydrated(function ($state, $record) {
                                // Evitar loops de atualização desnecessários
                                if ($record) {
                                    return $state !== $record->banned;
                                }

                                return true;
                            })
                            ->reactive()
                            ->columnSpanFull(),
                        Forms\Components\Textarea::make('ban_reason')
                            ->label('Motivo do Banimento')
                            ->placeholder('Descreva o motivo pelo qual o usuário foi banido...')
                            ->visible(fn (callable $get) => $get('banned'))
                            ->required(fn (callable $get) => $get('banned'))
                            ->columnSpanFull(),
                        Forms\Components\Toggle::make('is_demo_agent')
                            ->label('Influencer')
                            ->columnSpanFull(),
                        Forms\Components\Toggle::make('status')
                            ->label('Status')
                            ->default(true)
                            ->columnSpanFull(),
                        Forms\Components\Toggle::make('block_live_games')
                            ->label('Bloquear Jogos ao Vivo')
                            ->helperText('Bloqueia jogos ao vivo dos provedores Evolution, Creedz e Sagaming')
                            ->default(false)
                            ->columnSpanFull(),
                        Forms\Components\Toggle::make('block_skill_games')
                            ->label('Bloquear Jogos de Habilidade')
                            ->helperText('Bloqueia jogos de habilidade do provedor VGames')
                            ->default(false)
                            ->columnSpanFull(),
                        Forms\Components\Toggle::make('block_deposits')
                            ->label('Bloquear Depósitos')
                            ->helperText('Impede o usuário de realizar novos depósitos')
                            ->default(false)
                            ->columnSpanFull(),
                        Forms\Components\Toggle::make('kyc_required')
                            ->label('Verificação KYC Obrigatória')
                            ->helperText('Quando desabilitado, este usuário pode sacar sem verificação de documentos')
                            ->default(true)
                            ->columnSpanFull(),
                    ]),
                Forms\Components\Section::make('Limites de Saque')
                    ->schema([
                        Forms\Components\TextInput::make('daily_withdrawal_limit')
                            ->label('Limite Diário de Saque (€)')
                            ->helperText('Deixe em branco para usar o limite global')
                            ->numeric()
                            ->minValue(0)
                            ->prefix('€'),
                        Forms\Components\TextInput::make('daily_withdrawal_count_limit')
                            ->label('Limite de Quantidade de Saques Diários')
                            ->helperText('Deixe em branco para usar o limite global')
                            ->numeric()
                            ->minValue(0),
                        Forms\Components\TextInput::make('withdrawal_count_today')
                            ->label('Saques Realizados Hoje')
                            ->disabled()
                            ->dehydrated(false),
                        Forms\Components\TextInput::make('withdrawal_amount_today')
                            ->label('Valor Total Sacado Hoje')
                            ->disabled()
                            ->dehydrated(false)
                            ->prefix('€'),
                    ])->columns(2),
                Forms\Components\Section::make()
                    ->schema([
                        TextInput::make('password')
                            ->label('Senha')
                            ->placeholder('Digite a senha')
                            ->password()
                            ->confirmed()
                            ->required(fn (string $operation): bool => $operation === 'create')
                            ->maxLength(191),
                        TextInput::make('password_confirmation')
                            ->label('Confirme Senha')
                            ->placeholder('Confirme sua senha')
                            ->required(fn (string $operation): bool => $operation === 'create')
                            ->password()
                            ->maxLength(191),
                    ])->columns(2),
            ]);
    }

    /*** @param Table $table
     * @return Table
     */
    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('created_at', 'desc')
            ->modifyQueryUsing(function (Builder $query) {
                // Subquery to get the total deposits for each referred user, grouped by the referrer (inviter)
                $indicatedDeposits = DB::table('users as indicated_users')
                    ->join('deposits', 'indicated_users.id', '=', 'deposits.user_id')
                    ->select('indicated_users.inviter as inviter_id', DB::raw('SUM(deposits.amount) as total_indicated_deposits'))
                    ->where('indicated_users.is_demo_agent', 0)
                    ->where('deposits.status', 1)
                    ->groupBy('indicated_users.inviter');

                $query
                    // Join wallets to get balance components
                    ->leftJoin('wallets', 'users.id', '=', 'wallets.user_id')
                    // Join the pre-aggregated subquery for indicated deposits
                    ->leftJoinSub($indicatedDeposits, 'indicated_deposits_agg', function ($join) {
                        $join->on('users.id', '=', 'indicated_deposits_agg.inviter_id');
                    })
                    ->select(
                        'users.id',
                        'users.name',
                        'users.email',
                        'users.cpa_enabled',
                        'users.cpa_percentage',
                        'users.affiliate_cpa',
                        'users.email_verified_at',
                        'users.created_at',
                        'users.updated_at',
                        // Calculate total balance
                        DB::raw('COALESCE(wallets.balance, 0) + COALESCE(wallets.balance_bonus, 0) + COALESCE(wallets.balance_withdrawal, 0) as balance'),
                        // Use a simple correlated subquery for the user's own deposits
                        DB::raw('(SELECT COALESCE(SUM(amount), 0) FROM deposits WHERE deposits.user_id = users.id AND deposits.status = 1) as total_depositos'),
                        // Get the aggregated total from the subquery join
                        DB::raw('COALESCE(indicated_deposits_agg.total_indicated_deposits, 0) as total_depositos_indicados')
                    );
            })
            ->columns([
                Tables\Columns\TextColumn::make('id')
                    ->label('ID')
                    ->searchable(query: function (Builder $query, string $search): Builder {
                        return $query->where('users.id', 'like', "{$search}%");
                    })
                    ->sortable(),
                Tables\Columns\TextColumn::make('name')
                    ->label('Nome')
                    ->searchable(),
                Tables\Columns\TextColumn::make('email')
                    ->searchable(),
                Tables\Columns\TextColumn::make('balance')
                    ->label('Saldo')
                    ->money('EUR')
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_depositos')
                    ->label('Depósitos')
                    ->money('EUR')
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_depositos_indicados')
                    ->label('Total de Depósitos (Indicados)')
                    ->money('EUR')
                    ->sortable(),
                Tables\Columns\IconColumn::make('cpa_enabled')
                    ->label('CPA Ativo')
                    ->boolean()
                    ->trueIcon('heroicon-o-check-circle')
                    ->falseIcon('heroicon-o-x-circle'),
                Tables\Columns\TextColumn::make('cpa_percentage')
                    ->label('% CPA')
                    ->suffix('%'),
                Tables\Columns\TextColumn::make('affiliate_cpa')
                    ->label('CPA')
                    ->money('EUR'),
                Tables\Columns\TextColumn::make('mines_win_chance')
                    ->label('Mines %')
                    ->suffix('%')
                    ->placeholder('Aleatório')
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('email_verified_at')
                    ->dateTime()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable(),
                Tables\Columns\IconColumn::make('banned')
                    ->label('Banido')
                    ->boolean()
                    ->trueIcon('heroicon-o-x-circle')
                    ->falseIcon('heroicon-o-check-circle')
                    ->trueColor('danger')
                    ->falseColor('success')
                    ->sortable(),
                Tables\Columns\TextColumn::make('ban_reason')
                    ->label('Motivo do Banimento')
                    ->limit(50)
                    ->tooltip(function (\App\Models\User $record): ?string {
                        return $record->banned ? $record->ban_reason : null;
                    })
                    ->getStateUsing(function (\App\Models\User $record): string {
                        return $record->banned ? ($record->ban_reason ?? 'Sem motivo especificado') : 'N/A';
                    })
                    ->color(fn (\App\Models\User $record) => $record->banned ? 'danger' : 'gray')
                    ->toggleable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Data')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label('Atualização')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->headerActions([
                \Filament\Tables\Actions\Action::make('refresh_totals')
                    ->label('Atualizar Totais')
                    ->icon('heroicon-m-arrow-path')
                    ->action(function () {
                        Notification::make()
                            ->title('Tabela atualizada!')
                            ->success()
                            ->send();
                    }),
            ])
            ->filters([
                Filter::make('created_at')
                    ->form([
                        DatePicker::make('created_from')->label('Criado a partir de'),
                        DatePicker::make('created_until')->label('Criado até'),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['created_from'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '>=', $date),
                            )
                            ->when(
                                $data['created_until'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '<=', $date),
                            );
                    })
                    ->indicateUsing(function (array $data): array {
                        $indicators = [];

                        if ($data['created_from'] ?? null) {
                            $indicators['created_from'] = 'Criado a partir de '.Carbon::parse($data['created_from'])->toFormattedDateString();
                        }

                        if ($data['created_until'] ?? null) {
                            $indicators['created_until'] = 'Criado até '.Carbon::parse($data['created_until'])->toFormattedDateString();
                        }

                        return $indicators;
                    }),
            ])
            ->actions([
                Tables\Actions\Action::make('details')
                    ->label('Detalhes')
                    ->icon('heroicon-o-chart-bar')
                    ->color('gray')
                    ->action(function (User $user) {
                        return redirect()->to(route('filament.admin.resources.users.detail', ['record' => $user]));
                    }),
                Tables\Actions\ActionGroup::make([
                    Tables\Actions\ViewAction::make(),
                    Tables\Actions\EditAction::make(),
                    // Tables\Actions\DeleteAction::make(),
                ]),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                    Tables\Actions\BulkAction::make('enable_kyc_selected')
                        ->label('Ativar KYC')
                        ->icon('heroicon-o-shield-check')
                        ->color('success')
                        ->requiresConfirmation()
                        ->modalHeading('Ativar KYC para Usuários Selecionados')
                        ->modalDescription('Esta ação irá ativar a verificação KYC obrigatória para os usuários selecionados. Tem certeza?')
                        ->modalSubmitActionLabel('Sim, Ativar KYC')
                        ->action(function (\Illuminate\Database\Eloquent\Collection $records) {
                            $count = $records->count();
                            User::whereIn('id', $records->pluck('id'))->update(['kyc_required' => true]);

                            Notification::make()
                                ->title('KYC ativado com sucesso!')
                                ->body("KYC foi ativado para {$count} usuários selecionados.")
                                ->success()
                                ->send();
                        }),
                    Tables\Actions\BulkAction::make('disable_kyc_selected')
                        ->label('Desativar KYC')
                        ->icon('heroicon-o-shield-exclamation')
                        ->color('warning')
                        ->requiresConfirmation()
                        ->modalHeading('Desativar KYC para Usuários Selecionados')
                        ->modalDescription('Esta ação irá desativar a verificação KYC obrigatória para os usuários selecionados. Tem certeza?')
                        ->modalSubmitActionLabel('Sim, Desativar KYC')
                        ->action(function (\Illuminate\Database\Eloquent\Collection $records) {
                            $count = $records->count();
                            User::whereIn('id', $records->pluck('id'))->update(['kyc_required' => false]);

                            Notification::make()
                                ->title('KYC desativado com sucesso!')
                                ->body("KYC foi desativado para {$count} usuários selecionados.")
                                ->warning()
                                ->send();
                        }),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    /*** @return string[]
     */
    public static function getWidgets(): array
    {
        return [
            UserOverview::class,
        ];
    }

    /*** @return array|\Filament\Resources\Pages\PageRegistration[]
     */
    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Admin\Resources\UserResource\Pages\ListUsers::route('/'),
            'create' => \App\Filament\Admin\Resources\UserResource\Pages\CreateUser::route('/create'),
            'edit' => \App\Filament\Admin\Resources\UserResource\Pages\EditUser::route('/{record}/edit'),
            'view' => \App\Filament\Admin\Resources\UserResource\Pages\ViewUser::route('/{record}/view'),
            'detail' => \App\Filament\Admin\Resources\UserResource\Pages\DetailUser::route('/{record}/detail'),
            'password.change' => \App\Filament\Admin\Resources\UserResource\Pages\ChangePasswordUser::route('/{record}/password/change'),
        ];
    }
}
